spring:
  profiles:
      active: standalone
  security:
      user:
        name: wjq
        password: wjq
  application:
    name: eureka-server

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

# standalone
---
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://wjq:wjq@${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  profiles: standalone

# peers-1
---
server:
  port: 8761
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://wjq:wjq@peer2:8762/eureka/

# peers-2
---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
      service-url:
        defaultZone: http://wjq:wjq@peer1:8761/eureka/