server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: service-02
        uri: lb://service-02
        predicates:
        - Path=/service-02/**
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://wjq:wjq@peer1:8761/eureka/,http://wjq:wjq@peer2:8762/eureka/
